// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"cnft/internal/service/internal/dao/internal"
)

// internalNftEntityDao is internal type for wrapping internal DAO implements.
type internalNftEntityDao = *internal.NftEntityDao

// nftEntityDao is the data access object for table nft_entity.go.
// You can define custom methods on it to extend its functionality as you wish.
type nftEntityDao struct {
	internalNftEntityDao
}

var (
	// NftEntity is globally public accessible object for table nft_entity.go operations.
	NftEntity = nftEntityDao{
		internal.NewNftEntityDao(),
	}
)

// Fill with you ideas below.
