// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// NftEntity is the golang structure of table nft_entity for DAO operations like Where/Data.
type NftEntity struct {
	g.Meta     `orm:"table:nft_entity, do:true"`
	Id         interface{} // 主键
	EntityId   interface{} // 实体id##
	EntityType interface{} // 实体类型，1:装备##
	Token      interface{} // 区块链token##
	CreatedAt  interface{} // 创建时间##
	UpdatedAt  interface{} // 创建时间##
	DeletedAt  interface{} // 创建时间##
}
