// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// NftEntity is the golang structure for table nft_entity.
type NftEntity struct {
	Id         int64  `json:"id"          description:"主键"`          // 主键
	EntityId   string `json:"entity_id"   description:"实体id##"`      // 实体id##
	EntityType string `json:"entity_type" description:"实体类型，1:装备##"` // 实体类型，1:装备##
	Token      string `json:"token"       description:"区块链token##"`  // 区块链token##
	CreatedAt  int64  `json:"created_at"  description:"创建时间##"`      // 创建时间##
	UpdatedAt  int64  `json:"updated_at"  description:"创建时间##"`      // 创建时间##
	DeletedAt  int64  `json:"deleted_at"  description:"创建时间##"`      // 创建时间##
}
